// AUTO-GENERATED by scripts/extract-abis.mjs from
// protocol/lib/v2-core/out/InterestRateModel.sol/InterestRateModel.json
// Do not edit by hand.
export const interestRateModelAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "_minRate",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "_rateMultiplier",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "_highRateMultiplier",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "_optimalUtil",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getBorrowInterestFactor",
    "inputs": [
      {
        "name": "elapsedTime",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "borrowRate",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "getBorrowRate",
    "inputs": [
      {
        "name": "supply",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "borrows",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getUtilRate",
    "inputs": [
      {
        "name": "supply",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "borrows",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "highRateMultiplier",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "minRate",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "optimalUtil",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "rateMultiplier",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "InterestRateParamsSet",
    "inputs": [
      {
        "name": "minRate",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "rateMultiplier",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "highRateMultiplier",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "optimalUtil",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "ExpOverflow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "IRM_InvalidParamBound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "IRM_NoElapsedTime",
    "inputs": [
      {
        "name": "elapsedTime",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  }
] as const;
