// AUTO-GENERATED by scripts/extract-abis.mjs from
// protocol/lib/v2-core/out/LyraVolFeed.sol/LyraVolFeed.json
// Do not edit by hand.
export const lyraVolFeedAbi = [
  {
    "type": "constructor",
    "inputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "FEED_DATA_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "acceptData",
    "inputs": [
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "acceptOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "addSigner",
    "inputs": [
      {
        "name": "signer",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "isWhitelisted",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "domainSeparator",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getExpiryMinConfidence",
    "inputs": [
      {
        "name": "expiry",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "confidence",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getVol",
    "inputs": [
      {
        "name": "strike",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "expiry",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "vol",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "confidence",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hashFeedData",
    "inputs": [
      {
        "name": "feedData",
        "type": "tuple",
        "internalType": "struct IBaseLyraFeed.FeedData",
        "components": [
          {
            "name": "data",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "deadline",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "timestamp",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "signers",
            "type": "address[]",
            "internalType": "address[]"
          },
          {
            "name": "signatures",
            "type": "bytes[]",
            "internalType": "bytes[]"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "heartbeat",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isSigner",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingOwner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "requiredSigners",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setHeartbeat",
    "inputs": [
      {
        "name": "newHeartbeat",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setRequiredSigners",
    "inputs": [
      {
        "name": "newRequiredSigners",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "HeartbeatUpdated",
    "inputs": [
      {
        "name": "signer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "heartbeat",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferStarted",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RequiredSignersUpdated",
    "inputs": [
      {
        "name": "requiredSigners",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SignerUpdated",
    "inputs": [
      {
        "name": "signer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "isWhitelisted",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "VolDataUpdated",
    "inputs": [
      {
        "name": "expiry",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "volDetails",
        "type": "tuple",
        "indexed": false,
        "internalType": "struct ILyraVolFeed.VolDetails",
        "components": [
          {
            "name": "SVI_a",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "SVI_b",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "SVI_rho",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "SVI_m",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "SVI_sigma",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "SVI_fwd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "SVI_refTau",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "confidence",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "timestamp",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "VolSet",
    "inputs": [
      {
        "name": "strike",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "expiry",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "vol",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "confidence",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "BLF_DataExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BLF_DataTooOld",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BLF_DuplicatedSigner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BLF_InvalidRequiredSigners",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BLF_InvalidSignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BLF_InvalidSigner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BLF_InvalidTimestamp",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BLF_NotEnoughSigners",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BLF_SignatureSignersLengthMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LVF_InvalidConfidence",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LVF_InvalidVolDataTimestamp",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LVF_MissingExpiryData",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LnNegativeUndefined",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Overflow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SVI_InvalidParameters",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SVI_NoForwardPrice",
    "inputs": []
  }
] as const;
