// AUTO-GENERATED by scripts/extract-abis.mjs from
// protocol/lib/v2-core/out/LyraForwardFeed.sol/LyraForwardFeed.json
// Do not edit by hand.
export const lyraForwardFeedAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "_spotFeed",
        "type": "address",
        "internalType": "contract ISpotFeed"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "FEED_DATA_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "SETTLEMENT_TWAP_DURATION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "acceptData",
    "inputs": [
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "acceptOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "addSigner",
    "inputs": [
      {
        "name": "signer",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "isWhitelisted",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "domainSeparator",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getForwardPrice",
    "inputs": [
      {
        "name": "expiry",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getForwardPricePortions",
    "inputs": [
      {
        "name": "expiry",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "forwardFixedPortion",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "forwardVariablePortion",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "confidence",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getSettlementPrice",
    "inputs": [
      {
        "name": "expiry",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "settled",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "price",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hashFeedData",
    "inputs": [
      {
        "name": "feedData",
        "type": "tuple",
        "internalType": "struct IBaseLyraFeed.FeedData",
        "components": [
          {
            "name": "data",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "deadline",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "timestamp",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "signers",
            "type": "address[]",
            "internalType": "address[]"
          },
          {
            "name": "signatures",
            "type": "bytes[]",
            "internalType": "bytes[]"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "heartbeat",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isSigner",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "maxExpiry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingOwner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "requiredSigners",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setHeartbeat",
    "inputs": [
      {
        "name": "newHeartbeat",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setMaxExpiry",
    "inputs": [
      {
        "name": "_maxExpiry",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setRequiredSigners",
    "inputs": [
      {
        "name": "newRequiredSigners",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setSettlementHeartbeat",
    "inputs": [
      {
        "name": "_settlementHeartbeat",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setSpotFeed",
    "inputs": [
      {
        "name": "_spotFeed",
        "type": "address",
        "internalType": "contract ISpotFeed"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "settlementHeartbeat",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "spotFeed",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ISpotFeed"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "ForwardDataUpdated",
    "inputs": [
      {
        "name": "expiry",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "fwdDetails",
        "type": "tuple",
        "indexed": false,
        "internalType": "struct ILyraForwardFeed.ForwardDetails",
        "components": [
          {
            "name": "fwdSpotDifference",
            "type": "int96",
            "internalType": "int96"
          },
          {
            "name": "confidence",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "timestamp",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "name": "settlementDetails",
        "type": "tuple",
        "indexed": false,
        "internalType": "struct ILyraForwardFeed.SettlementDetails",
        "components": [
          {
            "name": "settlementStartAggregate",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "currentSpotAggregate",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "HeartbeatUpdated",
    "inputs": [
      {
        "name": "signer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "heartbeat",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MaxExpiryUpdated",
    "inputs": [
      {
        "name": "maxExpiry",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferStarted",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RequiredSignersUpdated",
    "inputs": [
      {
        "name": "requiredSigners",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SettlementHeartbeatUpdated",
    "inputs": [
      {
        "name": "settlementHeartbeat",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SettlementPriceSet",
    "inputs": [
      {
        "name": "expiry",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "settlementPrice",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SignerUpdated",
    "inputs": [
      {
        "name": "signer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "isWhitelisted",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SpotFeedUpdated",
    "inputs": [
      {
        "name": "spotFeed",
        "type": "address",
        "indexed": false,
        "internalType": "contract ISpotFeed"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "BLF_DataExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BLF_DataTooOld",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BLF_DuplicatedSigner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BLF_InvalidRequiredSigners",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BLF_InvalidSignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BLF_InvalidSigner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BLF_InvalidTimestamp",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BLF_NotEnoughSigners",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BLF_SignatureSignersLengthMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LFF_ExpiryTooFarInFuture",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LFF_InvalidConfidence",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LFF_InvalidDataTimestampForSettlement",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LFF_InvalidFwdDataTimestamp",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LFF_InvalidSettlementData",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LFF_MissingExpiryData",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LFF_SettlementDataTooOld",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotExpired",
    "inputs": [
      {
        "name": "expiry",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "timeNow",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  }
] as const;
