// AUTO-GENERATED by scripts/extract-abis.mjs from
// protocol/lib/v2-core/out/StandardManager.sol/StandardManager.json
// Do not edit by hand.
export const standardManagerAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "subAccounts_",
        "type": "address",
        "internalType": "contract ISubAccounts"
      },
      {
        "name": "cashAsset_",
        "type": "address",
        "internalType": "contract ICashAsset"
      },
      {
        "name": "_dutchAuction",
        "type": "address",
        "internalType": "contract IDutchAuction"
      },
      {
        "name": "_viewer",
        "type": "address",
        "internalType": "contract ISRMPortfolioViewer"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "accId",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "acceptOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "adjustmentsPaused",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "assetDetails",
    "inputs": [
      {
        "name": "asset",
        "type": "address",
        "internalType": "contract IAsset"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IStandardManager.AssetDetail",
        "components": [
          {
            "name": "isWhitelisted",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "assetType",
            "type": "uint8",
            "internalType": "enum IStandardManager.AssetType"
          },
          {
            "name": "marketId",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "assetMap",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "assetType",
        "type": "uint8",
        "internalType": "enum IStandardManager.AssetType"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IAsset"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "baseMarginParams",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "marginFactor",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "IMScale",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "borrowingEnabled",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "cashAsset",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ICashAsset"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "createMarket",
    "inputs": [
      {
        "name": "_marketName",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "marketId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "depegParams",
    "inputs": [],
    "outputs": [
      {
        "name": "threshold",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "depegFactor",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "executeBid",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "liquidatorId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "portion",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "bidAmount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "reservedCash",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "feeBypassedCaller",
    "inputs": [
      {
        "name": "sender",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "feeCharged",
    "inputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "feeRecipientAcc",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getIsolatedMargin",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "strike",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "expiry",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "isCall",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "balance",
        "type": "int256",
        "internalType": "int256"
      },
      {
        "name": "isInitial",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [
      {
        "name": "margin",
        "type": "int256",
        "internalType": "int256"
      },
      {
        "name": "markToMarket",
        "type": "int256",
        "internalType": "int256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMargin",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "isInitial",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [
      {
        "name": "margin",
        "type": "int256",
        "internalType": "int256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMarginAndMarkToMarket",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "isInitial",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "margin",
        "type": "int256",
        "internalType": "int256"
      },
      {
        "name": "markToMarket",
        "type": "int256",
        "internalType": "int256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMarketFeeds",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ISpotFeed"
      },
      {
        "name": "",
        "type": "address",
        "internalType": "contract IForwardFeed"
      },
      {
        "name": "",
        "type": "address",
        "internalType": "contract IVolFeed"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "guardian",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "handleAdjustment",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "tradeId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "assetDeltas",
        "type": "tuple[]",
        "internalType": "struct ISubAccounts.AssetDelta[]",
        "components": [
          {
            "name": "asset",
            "type": "address",
            "internalType": "contract IAsset"
          },
          {
            "name": "subId",
            "type": "uint96",
            "internalType": "uint96"
          },
          {
            "name": "delta",
            "type": "int256",
            "internalType": "int256"
          }
        ]
      },
      {
        "name": "managerData",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "lastMarketId",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "liquidation",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IDutchAuction"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "maxAccountSize",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "minOIFee",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "optionMarginParams",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "maxSpotReq",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "minSpotReq",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "mmCallSpotReq",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "mmPutSpotReq",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "MMPutMtMReq",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "unpairedIMScale",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "unpairedMMScale",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "mmOffsetScale",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "oracleContingencyParams",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "perpThreshold",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "optionThreshold",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "baseThreshold",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "OCFactor",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "payLiquidationFee",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "recipient",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "cashAmount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "pendingOwner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "perpMarginRequirements",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "mmPerpReq",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "imPerpReq",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setAdjustmentsPaused",
    "inputs": [
      {
        "name": "_paused",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setBaseAssetMarginFactor",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "marginFactor",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "initialMarginMultiplier",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setBorrowingEnabled",
    "inputs": [
      {
        "name": "enabled",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDepegParameters",
    "inputs": [
      {
        "name": "params",
        "type": "tuple",
        "internalType": "struct IStandardManager.DepegParams",
        "components": [
          {
            "name": "threshold",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "depegFactor",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setFeeBypassedCaller",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "bypassed",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setFeeRecipient",
    "inputs": [
      {
        "name": "_newAcc",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setGuardian",
    "inputs": [
      {
        "name": "_guardian",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setLiquidation",
    "inputs": [
      {
        "name": "_liquidation",
        "type": "address",
        "internalType": "contract IDutchAuction"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setMaxAccountSize",
    "inputs": [
      {
        "name": "_maxAccountSize",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setMinOIFee",
    "inputs": [
      {
        "name": "newMinOIFee",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setOptionMarginParams",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "params",
        "type": "tuple",
        "internalType": "struct IStandardManager.OptionMarginParams",
        "components": [
          {
            "name": "maxSpotReq",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minSpotReq",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "mmCallSpotReq",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "mmPutSpotReq",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "MMPutMtMReq",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "unpairedIMScale",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "unpairedMMScale",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "mmOffsetScale",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setOracleContingencyParams",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "params",
        "type": "tuple",
        "internalType": "struct IStandardManager.OracleContingencyParams",
        "components": [
          {
            "name": "perpThreshold",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "optionThreshold",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "baseThreshold",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "OCFactor",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setOraclesForMarket",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "spotFeed",
        "type": "address",
        "internalType": "contract ISpotFeed"
      },
      {
        "name": "forwardFeed",
        "type": "address",
        "internalType": "contract IForwardFeed"
      },
      {
        "name": "volFeed",
        "type": "address",
        "internalType": "contract IVolFeed"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setPerpMarginRequirements",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "_mmPerpReq",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "_imPerpReq",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setStableFeed",
    "inputs": [
      {
        "name": "_stableFeed",
        "type": "address",
        "internalType": "contract ISpotFeed"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setTrustedRiskAssessor",
    "inputs": [
      {
        "name": "riskAssessor",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "trusted",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setWhitelistedCallee",
    "inputs": [
      {
        "name": "callee",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "whitelisted",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "settleInterest",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "settleOptions",
    "inputs": [
      {
        "name": "option",
        "type": "address",
        "internalType": "contract IOptionAsset"
      },
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "settlePerpsWithIndex",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "stableFeed",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ISpotFeed"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "subAccounts",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ISubAccounts"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "trustedRiskAssessor",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "viewer",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IBasePortfolioViewer"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "whitelistAsset",
    "inputs": [
      {
        "name": "_asset",
        "type": "address",
        "internalType": "contract IAsset"
      },
      {
        "name": "_marketId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "_type",
        "type": "uint8",
        "internalType": "enum IStandardManager.AssetType"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "AdjustmentsPausedSet",
    "inputs": [
      {
        "name": "paused",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AssetWhitelisted",
    "inputs": [
      {
        "name": "asset",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "marketId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "assetType",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum IStandardManager.AssetType"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BaseMarginParamsSet",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "baseAssetMarginFactor",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "baseAssetIMScale",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BorrowingEnabled",
    "inputs": [
      {
        "name": "borrowingEnabled",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CalleeWhitelisted",
    "inputs": [
      {
        "name": "callee",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DepegParametersSet",
    "inputs": [
      {
        "name": "threshold",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "depegFactor",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FeeBypassedCallerSet",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "bypassed",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FeeRecipientSet",
    "inputs": [
      {
        "name": "_newAcc",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "GuardianSet",
    "inputs": [
      {
        "name": "guardian",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "LiquidationSet",
    "inputs": [
      {
        "name": "liquidation",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MarketCreated",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "marketName",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MaxAccountSizeUpdated",
    "inputs": [
      {
        "name": "maxAccountSize",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MinOIFeeSet",
    "inputs": [
      {
        "name": "minOIFee",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OptionMarginParamsSet",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "maxSpotReq",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "minSpotReq",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "mmCallSpotReq",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "mmPutSpotReq",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "MMPutMtMReq",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "unpairedIMScale",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "unpairedMMScale",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "mmOffsetScale",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OptionSettled",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "option",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "subId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "amount",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "value",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OracleContingencySet",
    "inputs": [
      {
        "name": "prepThreshold",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "optionThreshold",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "baseThreshold",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "OCFactor",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OraclesSet",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "spotOracle",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "forwardOracle",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "volFeed",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferStarted",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PerpMarginRequirementsSet",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "perpMMRequirement",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "perpIMRequirement",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PerpSettled",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "perp",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "pnl",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "funding",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "StableFeedUpdated",
    "inputs": [
      {
        "name": "stableFeed",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TrustedRiskAssessorUpdated",
    "inputs": [
      {
        "name": "riskAssessor",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "trusted",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "BM_AccountUnderLiquidation",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BM_AdjustmentsPaused",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BM_AssetCapExceeded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BM_GuardianOnly",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BM_InvalidBidPortion",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BM_InvalidLiquidation",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BM_InvalidMaxAccountSize",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BM_MinOIFeeTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BM_NotImplemented",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BM_OnlyAccounts",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BM_OnlyLiquidationModule",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BM_UnauthorizedCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SRM_InvalidBaseDiscountFactor",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SRM_InvalidDepegParams",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SRM_InvalidOptionMarginParams",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SRM_InvalidOracleContingencyParams",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SRM_InvalidPerpMarginParams",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SRM_MarketNotCreated",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SRM_NoForwardPrice",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SRM_NoNegativeCash",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SRM_NotAccounts",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SRM_NotWhitelistManager",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SRM_PortfolioBelowMargin",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SRM_TooManyAssets",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SRM_UnsupportedAsset",
    "inputs": []
  }
] as const;
