// AUTO-GENERATED by scripts/extract-abis.mjs from
// protocol/lib/v2-core/out/SubAccounts.sol/SubAccounts.json
// Do not edit by hand.
export const subAccountsAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "name_",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "symbol_",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "approve",
    "inputs": [
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "assetAdjustment",
    "inputs": [
      {
        "name": "adjustment",
        "type": "tuple",
        "internalType": "struct ISubAccounts.AssetAdjustment",
        "components": [
          {
            "name": "acc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "asset",
            "type": "address",
            "internalType": "contract IAsset"
          },
          {
            "name": "subId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "amount",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "assetData",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "triggerAssetHook",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "managerData",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "postAdjustmentBalance",
        "type": "int256",
        "internalType": "int256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "balanceAndOrder",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "asset",
        "type": "address",
        "internalType": "contract IAsset"
      },
      {
        "name": "subId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "balance",
        "type": "int240",
        "internalType": "int240"
      },
      {
        "name": "order",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "balanceOf",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "createAccount",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_manager",
        "type": "address",
        "internalType": "contract IManager"
      }
    ],
    "outputs": [
      {
        "name": "newId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "createAccountWithApproval",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "spender",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_manager",
        "type": "address",
        "internalType": "contract IManager"
      }
    ],
    "outputs": [
      {
        "name": "newId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "domainSeparator",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getAccountBalances",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "assetBalances",
        "type": "tuple[]",
        "internalType": "struct ISubAccounts.AssetBalance[]",
        "components": [
          {
            "name": "asset",
            "type": "address",
            "internalType": "contract IAsset"
          },
          {
            "name": "subId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "balance",
            "type": "int256",
            "internalType": "int256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getApproved",
    "inputs": [
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getBalance",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "asset",
        "type": "address",
        "internalType": "contract IAsset"
      },
      {
        "name": "subId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "balance",
        "type": "int256",
        "internalType": "int256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getUniqueAssets",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "uniqueAssets",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "heldAssets",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "asset",
        "type": "address",
        "internalType": "contract IAsset"
      },
      {
        "name": "subId",
        "type": "uint96",
        "internalType": "uint96"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "invalidateUnorderedNonces",
    "inputs": [
      {
        "name": "wordPos",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "mask",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "isApprovedForAll",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "operator",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "lastAccountId",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "lastAccountTradeId",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "tradeId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "lastTradeId",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "manager",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IManager"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "managerAdjustment",
    "inputs": [
      {
        "name": "adjustment",
        "type": "tuple",
        "internalType": "struct ISubAccounts.AssetAdjustment",
        "components": [
          {
            "name": "acc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "asset",
            "type": "address",
            "internalType": "contract IAsset"
          },
          {
            "name": "subId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "amount",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "assetData",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "postAdjustmentBalance",
        "type": "int256",
        "internalType": "int256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "name",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "negativeAssetAllowance",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "asset",
        "type": "address",
        "internalType": "contract IAsset"
      },
      {
        "name": "delegate",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "negativeSubIdAllowance",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "asset",
        "type": "address",
        "internalType": "contract IAsset"
      },
      {
        "name": "subId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "delegate",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "nonceBitmap",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "wordPosition",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "nonce",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ownerOf",
    "inputs": [
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "permit",
    "inputs": [
      {
        "name": "allowancePermit",
        "type": "tuple",
        "internalType": "struct IAllowances.PermitAllowance",
        "components": [
          {
            "name": "delegate",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "nonce",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "accountId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "deadline",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "assetAllowances",
            "type": "tuple[]",
            "internalType": "struct IAllowances.AssetAllowance[]",
            "components": [
              {
                "name": "asset",
                "type": "address",
                "internalType": "contract IAsset"
              },
              {
                "name": "positive",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "negative",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          },
          {
            "name": "subIdAllowances",
            "type": "tuple[]",
            "internalType": "struct IAllowances.SubIdAllowance[]",
            "components": [
              {
                "name": "asset",
                "type": "address",
                "internalType": "contract IAsset"
              },
              {
                "name": "subId",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "positive",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "negative",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          }
        ]
      },
      {
        "name": "signature",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "permitAndSubmitTransfer",
    "inputs": [
      {
        "name": "assetTransfer",
        "type": "tuple",
        "internalType": "struct ISubAccounts.AssetTransfer",
        "components": [
          {
            "name": "fromAcc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "toAcc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "asset",
            "type": "address",
            "internalType": "contract IAsset"
          },
          {
            "name": "subId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "amount",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "assetData",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "managerData",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "allowancePermit",
        "type": "tuple",
        "internalType": "struct IAllowances.PermitAllowance",
        "components": [
          {
            "name": "delegate",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "nonce",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "accountId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "deadline",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "assetAllowances",
            "type": "tuple[]",
            "internalType": "struct IAllowances.AssetAllowance[]",
            "components": [
              {
                "name": "asset",
                "type": "address",
                "internalType": "contract IAsset"
              },
              {
                "name": "positive",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "negative",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          },
          {
            "name": "subIdAllowances",
            "type": "tuple[]",
            "internalType": "struct IAllowances.SubIdAllowance[]",
            "components": [
              {
                "name": "asset",
                "type": "address",
                "internalType": "contract IAsset"
              },
              {
                "name": "subId",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "positive",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "negative",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          }
        ]
      },
      {
        "name": "signature",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "tradeId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "permitAndSubmitTransfers",
    "inputs": [
      {
        "name": "assetTransfers",
        "type": "tuple[]",
        "internalType": "struct ISubAccounts.AssetTransfer[]",
        "components": [
          {
            "name": "fromAcc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "toAcc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "asset",
            "type": "address",
            "internalType": "contract IAsset"
          },
          {
            "name": "subId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "amount",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "assetData",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "managerData",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "allowancePermits",
        "type": "tuple[]",
        "internalType": "struct IAllowances.PermitAllowance[]",
        "components": [
          {
            "name": "delegate",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "nonce",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "accountId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "deadline",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "assetAllowances",
            "type": "tuple[]",
            "internalType": "struct IAllowances.AssetAllowance[]",
            "components": [
              {
                "name": "asset",
                "type": "address",
                "internalType": "contract IAsset"
              },
              {
                "name": "positive",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "negative",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          },
          {
            "name": "subIdAllowances",
            "type": "tuple[]",
            "internalType": "struct IAllowances.SubIdAllowance[]",
            "components": [
              {
                "name": "asset",
                "type": "address",
                "internalType": "contract IAsset"
              },
              {
                "name": "subId",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "positive",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "negative",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          }
        ]
      },
      {
        "name": "signatures",
        "type": "bytes[]",
        "internalType": "bytes[]"
      }
    ],
    "outputs": [
      {
        "name": "tradeId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "positiveAssetAllowance",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "asset",
        "type": "address",
        "internalType": "contract IAsset"
      },
      {
        "name": "delegate",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "positiveSubIdAllowance",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "asset",
        "type": "address",
        "internalType": "contract IAsset"
      },
      {
        "name": "subId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "delegate",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "safeTransferFrom",
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "safeTransferFrom",
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setApprovalForAll",
    "inputs": [
      {
        "name": "operator",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "approved",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setAssetAllowances",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "delegate",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "allowances",
        "type": "tuple[]",
        "internalType": "struct IAllowances.AssetAllowance[]",
        "components": [
          {
            "name": "asset",
            "type": "address",
            "internalType": "contract IAsset"
          },
          {
            "name": "positive",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "negative",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setSubIdAllowances",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "delegate",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "allowances",
        "type": "tuple[]",
        "internalType": "struct IAllowances.SubIdAllowance[]",
        "components": [
          {
            "name": "asset",
            "type": "address",
            "internalType": "contract IAsset"
          },
          {
            "name": "subId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "positive",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "negative",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "submitTransfer",
    "inputs": [
      {
        "name": "assetTransfer",
        "type": "tuple",
        "internalType": "struct ISubAccounts.AssetTransfer",
        "components": [
          {
            "name": "fromAcc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "toAcc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "asset",
            "type": "address",
            "internalType": "contract IAsset"
          },
          {
            "name": "subId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "amount",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "assetData",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "managerData",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "tradeId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "submitTransfers",
    "inputs": [
      {
        "name": "assetTransfers",
        "type": "tuple[]",
        "internalType": "struct ISubAccounts.AssetTransfer[]",
        "components": [
          {
            "name": "fromAcc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "toAcc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "asset",
            "type": "address",
            "internalType": "contract IAsset"
          },
          {
            "name": "subId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "amount",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "assetData",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "managerData",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "tradeId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "supportsInterface",
    "inputs": [
      {
        "name": "interfaceId",
        "type": "bytes4",
        "internalType": "bytes4"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "symbol",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "tokenURI",
    "inputs": [
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transferFrom",
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "AccountBurned",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "accountId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "manager",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AccountCreated",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "accountId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "manager",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AccountManagerChanged",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "oldManager",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newManager",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Approval",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "approved",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "tokenId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ApprovalForAll",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "operator",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "approved",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AssetTransferred",
    "inputs": [
      {
        "name": "fromAcc",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "toAcc",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "asset",
        "type": "address",
        "indexed": false,
        "internalType": "contract IAsset"
      },
      {
        "name": "subId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "amount",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "assetData",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "tradeId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BalanceAdjusted",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "manager",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "assetAndSubId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "amount",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "preBalance",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "postBalance",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "tradeId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Transfer",
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "tokenId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "UnorderedNonceInvalidated",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "wordPos",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "mask",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AC_CannotChangeToSameManager",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "AC_CannotTransferAssetToOneself",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "AC_InvalidNonce",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AC_InvalidPermitSignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AC_NotOwnerOrERC721Approved",
    "inputs": [
      {
        "name": "spender",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "manager",
        "type": "address",
        "internalType": "contract IManager"
      },
      {
        "name": "approved",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "AC_OnlyAsset",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AC_OnlyManager",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AC_SignatureExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AC_TooManyTransfers",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DL_DeltasTooLong",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotEnoughSubIdOrAssetAllowances",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amount",
        "type": "int256",
        "internalType": "int256"
      },
      {
        "name": "subIdAllowance",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "assetAllowance",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  }
] as const;
