import type { RiskLimitCode } from "../risk/exposures.js";

export type DeclineReasonCode =
  | "INVALID_RFQ"
  | "INVALID_POLICY"
  | "INVALID_PORTFOLIO_STATE"
  | "UNVERIFIED_INSTRUMENT"
  | "UNSUPPORTED_ASSET"
  | "UNSUPPORTED_CURRENCY"
  | "UNSUPPORTED_DIRECTION"
  | "UNSUPPORTED_OPTION_TYPE"
  | "INVALID_SIZE"
  | "SIZE_OUTSIDE_LIMIT"
  | "OPTION_EXPIRED"
  | "EXPIRY_OUTSIDE_LIMIT"
  | "MONEYNESS_OUTSIDE_LIMIT"
  | "QUOTE_WINDOW_TOO_SHORT"
  | "QUOTE_WINDOW_TOO_LONG"
  | "ACCEPTANCE_WINDOW_INVALID"
  | "OPTION_MARKET_DATA_UNHEALTHY"
  | "OPTION_MARKET_DATA_STALE"
  | "HEDGE_MARKET_DATA_STALE"
  | "MARKET_DATA_FROM_FUTURE"
  | "MARKET_CONFIDENCE_TOO_LOW"
  | "INVALID_MARKET_DATA"
  | "VOLATILITY_OUTSIDE_LIMIT"
  | "RATE_OUTSIDE_LIMIT"
  | "FORWARD_SPOT_DIVERGENCE"
  | "HEDGE_VENUE_UNHEALTHY"
  | "HEDGE_MARK_ORACLE_DIVERGENCE"
  | "CROSS_VENUE_SPOT_DIVERGENCE"
  | "HEDGE_INSTRUMENT_MISMATCH"
  | "HEDGE_BOOK_INVALID"
  | "HEDGE_SPREAD_TOO_WIDE"
  | "HEDGE_DEPTH_INSUFFICIENT"
  | "HEDGE_ORDER_BELOW_MINIMUM"
  | "HEDGE_MARGIN_INSUFFICIENT"
  | "HEDGE_RECONCILIATION_UNHEALTHY"
  | "HEDGE_BACKLOG_PRESENT"
  | "RESIDUAL_DELTA_LIMIT"
  | "NON_POSITIVE_RESERVATION_BID"
  | "BID_BELOW_MINIMUM"
  | RiskLimitCode;

export interface GateCheck {
  readonly gate: string;
  readonly passed: boolean;
  readonly declineCode: DeclineReasonCode;
  readonly detail: string;
  readonly observed?: number | string | boolean;
  readonly limit?: number | string | boolean;
}
