#!/usr/bin/env node
/**
 * Extracts ABIs from the vendored forge artifacts (READ-ONLY inputs) into
 * src/abis/*.ts as viem-style `as const` exports.
 *
 * Sources:
 *   protocol/lib/v2-matching/out  (Matching + modules)
 *   protocol/lib/v2-core/out      (core assets, manager, feeds, mocks)
 *
 * Rebuild artifacts with `forge build` inside each vendored repo if missing.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const sharedRoot = resolve(__dirname, "..");
// services/shared -> repo root is two levels up
const repoRoot = resolve(sharedRoot, "..", "..");

const MATCHING_OUT = join(repoRoot, "protocol", "lib", "v2-matching", "out");
const CORE_OUT = join(repoRoot, "protocol", "lib", "v2-core", "out");

/** [outDir, "<File>.sol/<Contract>.json", exportName] */
const TARGETS = [
  // v2-matching
  [MATCHING_OUT, "Matching.sol/Matching.json", "matchingAbi"],
  [MATCHING_OUT, "ActionVerifier.sol/ActionVerifier.json", "actionVerifierAbi"],
  [MATCHING_OUT, "RfqModule.sol/RfqModule.json", "rfqModuleAbi"],
  [MATCHING_OUT, "TradeModule.sol/TradeModule.json", "tradeModuleAbi"],
  [MATCHING_OUT, "DepositModule.sol/DepositModule.json", "depositModuleAbi"],
  [MATCHING_OUT, "WithdrawalModule.sol/WithdrawalModule.json", "withdrawalModuleAbi"],
  [MATCHING_OUT, "TransferModule.sol/TransferModule.json", "transferModuleAbi"],
  // v2-core
  [CORE_OUT, "SubAccounts.sol/SubAccounts.json", "subAccountsAbi"],
  [CORE_OUT, "CashAsset.sol/CashAsset.json", "cashAssetAbi"],
  [CORE_OUT, "OptionAsset.sol/OptionAsset.json", "optionAssetAbi"],
  [CORE_OUT, "WrappedERC20Asset.sol/WrappedERC20Asset.json", "wrappedErc20AssetAbi"],
  [CORE_OUT, "StandardManager.sol/StandardManager.json", "standardManagerAbi"],
  [CORE_OUT, "InterestRateModel.sol/InterestRateModel.json", "interestRateModelAbi"],
  [CORE_OUT, "SecurityModule.sol/SecurityModule.json", "securityModuleAbi"],
  // feeds
  [CORE_OUT, "LyraSpotFeed.sol/LyraSpotFeed.json", "lyraSpotFeedAbi"],
  [CORE_OUT, "LyraForwardFeed.sol/LyraForwardFeed.json", "lyraForwardFeedAbi"],
  [CORE_OUT, "LyraVolFeed.sol/LyraVolFeed.json", "lyraVolFeedAbi"],
  [CORE_OUT, "LyraRateFeed.sol/LyraRateFeed.json", "lyraRateFeedAbi"],
  // tokens
  [CORE_OUT, "ERC20.sol/ERC20.json", "erc20Abi"],
  [CORE_OUT, "MockERC20.sol/MockERC20.json", "mockErc20Abi"],
];

const outDir = join(sharedRoot, "src", "abis");
mkdirSync(outDir, { recursive: true });

const indexLines = [
  "// AUTO-GENERATED by scripts/extract-abis.mjs — do not edit by hand.",
];

for (const [base, rel, exportName] of TARGETS) {
  const artifactPath = join(base, rel);
  if (!existsSync(artifactPath)) {
    console.error(
      `Missing forge artifact: ${artifactPath}\n` +
        `Run \`forge build\` in the corresponding vendored repo first.`,
    );
    process.exit(1);
  }
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  const abi = artifact.abi;
  if (!Array.isArray(abi)) {
    console.error(`Artifact ${artifactPath} has no abi array`);
    process.exit(1);
  }
  const fileBase = exportName.replace(/Abi$/, "");
  const body =
    `// AUTO-GENERATED by scripts/extract-abis.mjs from\n` +
    `// ${artifactPath.replace(repoRoot + "/", "")}\n` +
    `// Do not edit by hand.\n` +
    `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(outDir, `${fileBase}.ts`), body);
  indexLines.push(`export { ${exportName} } from "./${fileBase}.js";`);
  console.log(`wrote src/abis/${fileBase}.ts (${abi.length} entries)`);
}

writeFileSync(join(outDir, "index.ts"), indexLines.join("\n") + "\n");
console.log(`wrote src/abis/index.ts (${TARGETS.length} ABIs)`);
